services:
  python_backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: star-python-backend
    volumes:
      - ./python_backend:/app
      - ./python_backend/database.db:/app/database.db
      - ./python_backend/logs:/app/logs
    environment:
      - DATABASE_URL=sqlite:////app/database.db
      - UPLOAD_DIR=/app/uploads
      - LOG_DIR=/app/logs
    ports:
      - "8000:8000"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: star-nginx
    ports:
      - "8008:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./python_backend/uploads:/app/uploads:ro
    depends_on:
      - python_backend
    restart: unless-stopped

volumes:
  app-public:
